### ISSUE TITLE
Linking to managers by ID

### ISSUE THREAD

**Issue by roikles** [gravityflow/gravityflow#3]
Hi, I just bought the plugin because the features are fantastic, I have come across a little issue in the way that I would like to manage submissions.

We are currently building a site that has a couple of user levels. 'Users' and 'Managers'. These are created as needed and eventually there will be hundreds of managers plus the teams of users they manage.

I have a form called Timesheets which users fill in, this then needs to be sent using Gravity Flow to the correct manager.

What I cant figure out how to do is ensure that the right manager gets notified of forms filled in by their team without having to set up rules for every single manager. I currently have it set to the manager user role.

Currently I have a field in wp_usermeta called 'user_belongs_to' for each user and the value of this meta key is the 'id' of the correct manager. Is there a hook or action in the API that I can use to dynamically filter the assignee through to the right manager based on that meta entry?

Would I be best off adding an assignee field to the form (http://docs.gravityflow.io/article/9-can-i-allow-the-form-submitter-to-select-the-step-assignee) and populating that field dynamically or is there some other method that would be more appropriate?

Thanks!!

**Comment by roikles** [comment]
I found that the easiest way to achieve this was to use the new 'User' field type then set to 'Allow field to be populated dynamically' and set the 'parameter' to 'assignee'. I also set the User field to Admin-only so that it isnt visible on the front end. Finally I then dropped the following function into `functions.php` to dynamically fill the field in and it works great:

```
add_filter( 'gform_field_value_assignee', 'get_manager_id' );

function get_manager_id( $value ) {
    $user_id = get_current_user_id();
    $client_id = get_user_meta($user_id, 'candidate_belongs_to_client');
    return $client_id[0];
}
```

**Comment by stevehenty** [comment]
@roikles  There are a few ways you might go about this. Your way is fine. You could also use the [gravityflow_user_field](http://docs.gravityflow.io/article/82-gravityflowuserfield) filter.

If you have any further questions please open a support ticket and we'll be happy to help.

**Comment by joffcrabtree** [comment]
Mine might be a long winded way, but I am using Active Directory Integration to pull all users from the organisation. The manager is located in user meta as CN

//Allow dynamic population of manager ID (for user form field) using parameter manager_username
add_filter( 'gform_field_value_manager_userid', 'populate_manager_uid' );
function populate_manager_uid( $value ) {
    //Set $current user and load values
    global $user_ID;
	$user_data = get_userdata( $user_ID);
	//return $user_data->adi_department;
	$manager = get_user_meta( $user_ID, 'adi_manager', true);

	$args = array(  
        'meta_key'     => 'adi_cn',
        'meta_value'   => $manager,
        );
	$managers = get_users( $args );

	foreach($managers as $manager)
	{
		$id = $manager->ID;
	}
	return $id;

}
