### ISSUE TITLE
Multiple Signature fields

### ISSUE THREAD

**Issue by roikles** [gravityflow/gravityflow#5]
I found a minor issue today when combined with the Gravity forms signature add-on.

I have a timesheet submission form that is filled in by a user and sent through to a manager. It has two signature boxes, one for the user and one for admin.

I have setup the workflow so that there is a user-input step where admins can check over the user submission and add their signature if everything is ok.

In the user-input step I set the Editable fields to include the manager signature field but when viewed by managers there is just a blank space where the signature field should be and a javascript error:

`ss.js?ver=3.0.4:13 - Uncaught TypeError: Cannot read property 'nodeName' of null`

Playing around I have found that if I also include the user signature field in the list of 'Editable Fields' both signature boxes show up and are both editable, which is perfectly acceptable in my current workflow but I thought I would let you know of the issue.

**Comment by richardW8k** [comment]
Could you try updating to the latest build of the signature add-on available from https://www.gravityhelp.com/downloads/add-ons/

**Comment by roikles** [comment]
@richardW8k That has solved the issue perfectly! Looks like they fixed this on their side with version 3.0.5

**Comment by stevehenty** [comment]
Thanks for letting us know. If you have any further questions, please [open a support ticket](https://gravityflow.io/support/) and we'll be happy to help.
